import Head from 'next/head';
import { useEffect, useState } from 'react';
import { Concert_One } from 'next/font/google';
import { api } from '@/components/utils/api';
import { createPoller } from '@/components/utils/common';
import { GamePlay } from '@/components/Game';
import { Menu } from '@/components/Menu';
import { Game } from '@/components/utils/types';

const font = Concert_One({ weight: '400', subsets: ['latin'] });

export default function Home() {
  const [game, setGame] = useState<Game>({
    questionNo: -1,
    state: 'not-started',
    rounds: [],
    menu: {
      title: '',
      highlighted: 0,
      options: [],
    },
  });

  const { start, getData } = api();

  useEffect(() => {
    start().then(createPoller(() => getData(), setGame, 500));
  }, []);

  return (
    <>
      <Head>
        <title>Trivia Racing Game</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main
        className={`w-[100vw] h-[100vh] relative flex items-center justify-center ${font.className}`}
      >
        {game.state === 'not-started' && <Menu value={game.menu} />}
        {game.state !== 'not-started' && <GamePlay game={game} />}
      </main>
    </>
  );
}
